### ISSUE TITLE
Unable to login with MicrosoftAccount

### ISSUE THREAD

**Issue by aeisenberg** [ocilo/skype-http#116]
I started receiving the following error last night. My account is no longer able to log in to skype using this library. Is it possible that the api has changed?

```
Unable to login with MicrosoftAccount.
MicrosoftAccountLogin: Unable to login with MicrosoftAccount.
  caused by GetLiveToken: Unable to get the Live token for Skype
  caused by LiveTokenNotFound: Unable to find the Live token. This token is normally found in the HTML response as the value of the element with the id "t". This error may be caused by a change in the Microsoft login workflow. HTML page: "<html><head><noscript>JavaScript required to sign in<meta http-equiv=\"Refresh\" content=\"0; URL=https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033&uaid=08766b033f8f450ca7ad755e627193ec&client_flight=ReservedFlight33,ReservedFligh\"/></noscript><title>Continue</title><script type=\"text/javascript\">function OnBack(){}function OnNext(){}function DoSubmit(){var subt=false;if(!subt){subt=true;document.fmHF.submit();}}</script></head><body onload=\"javascript:DoSubmit();\"><form name=\"fmHF\" id=\"fmHF\" action=\"https://account.live.com/apps/upsell?app=Authenticator&mkt=EN-US&uiflavor=web&id=293290&ru=https://login.live.com/login.srf%3fid%3d293290%26opid%3d8F099F11057090DA%26opidt%3d1552929230\" method=\"post\" target=\"_top\"><input type=\"hidden\" name=\"client_flight\" id=\"client_flight\" value=\"ReservedFlight33,ReservedFligh\"><input type=\"hidden\" name=\"ipt\" id=\"ipt\" value=\"DU3HcN59A5aRRYHqRRY!A7pxEWFw7LWZ4Y!x1yNGsFfbHZTi4NIQPsjCeI*g21R3HB*lLAj9F9HHIdB8KQr9LFL2ETp46pT!YObubWX5Oma*DxSCS!W5M9r2mTqumIukKtjnu4hKqBFOW3uvPdVlkieVYhel1QiB3ZmwIMfTrHsbdh!Ogf8zDuFjTygkJYAIXU8cefAMOu62BXdHzGJu!yAEoI8MVJ4Gw6yq5ZrIu*tYzQ*4sPFLU8KynDh7fiDBF6Pf*8kiod0oiLkA47MlPT*!8k8mfTNHxoLCa5waRMNjDBtCZ7lq00rdTPxASLhdZvWlnv2d*bafEmrwnrwjKfdgMHVZaiGPdYLPFu7KPeUVsAb60pRs7eIRLMGmIAqM*NucQM088OjlZICfXU8hPuuHPvYuxkRxrdRJErU!VZ3eo*wqxgQdNhulH4E*Sf3mUx17KJZNLhYbuH*54FcJlFIMs9es0zqOX!fQRxc!P78s\"><input type=\"hidden\" name=\"pprid\" id=\"pprid\" value=\"e152605252064532\"><input type=\"hidden\" name=\"uaid\" id=\"uaid\" value=\"08766b033f8f450ca7ad755e627193ec\"></form></body></html>"
```

**Comment by ataliba** [comment]
I have the same problem here. I believe skype have a change on the api. 

<code>
'LiveTokenNotFound: Unable to find the Live token. This token is normally found in the HTML response as the value of the element with the id "t". This error may be caused by a change in the Microsoft login workflow. HTML page: "<html><head><noscript>JavaScript required to sign in<meta http-equiv=\\"Refresh\\" content=\\"0; URL=https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033&uaid=ebf7cb738e06496dbef4c3cb77b98c81&client_flight=ReservedFlight33,ReservedFligh\\"/></noscript><title>Continue</title><script type=\\"text/javascript\\">function OnBack(){}function OnNext(){}function DoSubmit(){var subt=false;if(!subt){subt=true;document.fmHF.submit();}}</script></head><body onload=\\"javascript:DoSubmit();\\"><form name=\\"fmHF\\" id=\\"fmHF\\" action=\\"https://account.live.com/identity/confirm?mkt=EN-US&uiflavor=web&id=293290&ru=https://login.live.com/login.srf%3fid%3d293290%26opid%3d31BF0D8BE11A8B34%26opidt%3d1559319149\\" method=\\"post\\" target=\\"_top\\"><input type=\\"hidden\\" name=\\"client_flight\\" id=\\"client_flight\\" value=\\"ReservedFlight33,ReservedFligh\\"><input type=\\"hidden\\" name=\\"ipt\\" id=\\"ipt\\" value=\\"Dfkc10s5ojPaqZ5LOx2d!g4Bs1n4jTySZsUvNenNoVPk!013SiO46E*fS4S5!ytTDML2!jq0eDepnPmBcUOtyolCH!sOmVlwQMLNWrDHSubbR6TjijRKJIJEDOzlSJNdGmWnt7fIyPL5RX3Crj5xTEHVRzmrMHreBJy67!pogEXASkWs8TGgVYSyt6jp!xu3XjrYyCqPsZopNX4E2rH8fFTeEF8fG20o2SGt8mT2A7CF2wsEe65hrxgDI9UEL79!XqJXhkWoCQ2DU2jtJUSZ!qPm3GPEPdTM7FUa5t95c9n2p28L3C2SFSurreaRJF*MvBCFRjZcjiZj65MQEI1MvUqs5T0hhPkYh24i229k9Hq6zB9DqXQqO8lQ8GRgbgmmRN*K0kiiCVS5Y981T92GFala2zc12y0fMu*Ec5YkqpAet3sDrMLa1j69hfbQIyVoAjyDx3HaTp2SvgaB1*3*Qhw7pL6f!MJYcFQpL5ZVTSky\\"><input type=\\"hidden\\" name=\\"pprid\\" id=\\"pprid\\" value=\\"164f908396258983\\"><input type=\\"hidden\\" name=\\"uaid\\" id=\\"uaid\\" value=\\"ebf7cb738e06496dbef4c3cb77b98c81\\"></form></body></html>"\n    at Object.create (/opt/skype/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/errors/microsoft-account/get-live-token.js:17:16)\n    at scrapLiveToken (/opt/skype/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:218:61)\n    at /opt/skype/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:137:20\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/skype/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:4:58)\n    at processTicksAndRejections (internal/process/task_queues.js:86:5)' },
     message:
      'GetLiveToken: Unable to get the Live token for Skype\n  caused by LiveTokenNotFound: Unable to find the Live token. This token is normally found in the HTML response as the value of the element with the id "t". This error may be caused by a change in the Microsoft login workflow. HTML page: "<html><head><noscript>JavaScript required to sign in<meta http-equiv=\\"Refresh\\" content=\\"0; URL=https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033&uaid=ebf7cb738e06496dbef4c3cb77b98c81&client_flight=ReservedFlight33,ReservedFligh\\"/></noscript><title>Continue</title><script type=\\"text/javascript\\">function OnBack(){}function OnNext(){}function DoSubmit(){var subt=false;if(!subt){subt=true;document.fmHF.submit();}}</script></head><body onload=\\"javascript:DoSubmit();\\"><form name=\\"fmHF\\" id=\\"fmHF\\" action=\\"https://account.live.com/identity/confirm?mkt=EN-US&uiflavor=web&id=293290&ru=https://login.live.com/login.srf%3fid%3d293290%26opid%3d31BF0D8BE11A8B34%26opidt%3d1559319149\\" method=\\"post\\" target=\\"_top\\"><input type=\\"hidden\\" name=\\"client_flight\\" id=\\"client_flight\\" value=\\"ReservedFlight33,ReservedFligh\\"><input type=\\"hidden\\" name=\\"ipt\\" id=\\"ipt\\" value=\\"Dfkc10s5ojPaqZ5LOx2d!g4Bs1n4jTySZsUvNenNoVPk!013SiO46E*fS4S5!ytTDML2!jq0eDepnPmBcUOtyolCH!sOmVlwQMLNWrDHSubbR6TjijRKJIJEDOzlSJNdGmWnt7fIyPL5RX3Crj5xTEHVRzmrMHreBJy67!pogEXASkWs8TGgVYSyt6jp!xu3XjrYyCqPsZopNX4E2rH8fFTeEF8fG20o2SGt8mT2A7CF2wsEe65hrxgDI9UEL79!XqJXhkWoCQ2DU2jtJUSZ!qPm3GPEPdTM7FUa5t95c9n2p28L3C2SFSurreaRJF*MvBCFRjZcjiZj65MQEI1MvUqs5T0hhPkYh24i229k9Hq6zB9DqXQqO8lQ8GRgbgmmRN*K0kiiCVS5Y981T92GFala2zc12y0fMu*Ec5YkqpAet3sDrMLa1j69hfbQIyVoAjyDx3HaTp2SvgaB1*3*Qhw7pL6f!MJYcFQpL5ZVTSky\\"><input type=\\"hidden\\" name=\\"pprid\\" id=\\"pprid\\" value=\\"164f908396258983\\"><input type=\\"hidden\\" name=\\"uaid\\" id=\\"uaid\\" value=\\"ebf7cb738e06496dbef4c3cb77b98c81\\"></form></body></html>"\n    at Object.create (/opt/skype/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/errors/microsoft-account/get-live-token.js:17:16)\n    at scrapLiveToken (/opt/skype/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:218:61)\n    at /opt/skype/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:137:20\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/skype/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:4:58)\n    at processTicksAndRejections (internal/process/task_queues.js:86:5)' } }
</code>

**Comment by aeisenberg** [comment]
So, I had stopped receiving this message for a few months, and as of Tuesday, I started receiving it again.

**Comment by aeisenberg** [comment]
Actually, I see what I need to do. When I get this error, I need to log on to through the website directly and click through a dialog or two before getting to the main site. Once you do that, then your account is in a good state again.
