### ISSUE TITLE
Package.json not JSON File

### ISSUE THREAD

**Issue by ProBukkit** [ocilo/skype-http#16]
"Tell the package author to fix their package.json file. JSON.parse"

**Comment by demurgos** [comment]
Hi,
Sorry for the late reply, I did not get (or missed) the Github notification. The library is currently "working" but not in a state that I am satisfied with so I am currently doing some updates. (Error handling, documentation)
As far as I can tell, the package.json file is valid, I was able to `npm install skype-http` on a fresh computer.
Could you check if the error is not related to your top-level package.json file ?

Did you close the issue because you managed to solve this ?

**Comment by ProBukkit** [comment]
Yes sorry my NPM was malfunctioning.
